### ISSUE TITLE
[FIX] Observation space tem tamanho: 345, mas a observação retornada a cada interação tem tamanho 336

### ISSUE THREAD

**Issue by brunoconterato** [bryanoliveira/soccer-twos-env#1]
![image](https://user-images.githubusercontent.com/11790806/139731391-d3aa9719-9aec-4c13-af5b-bf27cb30b96d.png)

#### Problema:
Observamos pelo diff do Github (imagem acima) que a observação retornada pelo game é 345, mas a cada step o Wrapper retorna observação de tamanho 336 (as demais observações são retornadas juntamente com o objeto info).

Dessa forma, se pegarmos o valor de env.observation_space.shape[0] teremos o valor de 345. Assim, ao criar nossos models, criamos a rede de tamanho 345 mas as observações a cada step vem de tamanho 336, ocasionando erro.

#### Possíveis Soluções:

1. O desenvolvedor criar a sua network do agente de tamanho estático igual a 336. Acredito que seria melhor ele obter o valor 336 dinamicamente corrigindo o valor de env.observation_space.shape[0];
2. Corrigir o valor de env.observation_space.shape[0];
3. Manter o valor de env.observation_space.shape[0] como sendo 345 e a cada step retornar todos os 345 valores na forma de observação para agente.

**Comment by bryanoliveira** [comment]
Boa @brunoconterato, obrigado por apontar o erro.
Corrigi na versão [0.1.2](https://github.com/bryanoliveira/soccer-twos-env/commit/8381cdeaa93e0dde66c89ffc418034136a0d0123).
