### ISSUE TITLE
default params total reward 0

### ISSUE THREAD

**Issue by vgainullin** [bryanoliveira/soccer-twos-env#4]
Thanks for starting this repo. Tried training a model with default parameters per README, currently getting on average 0 total reward. Do you know what the problem might be?

**Comment by bryanoliveira** [comment]
Hi @vgainullin!

Many things could be going wrong… I suggest you start trying building agents for the `variation=EnvType.team_vs_policy` since it's way easier for the training algorithm when compared to the default `multiagent_player`. [Here](https://github.com/bryanoliveira/ceia-rl-tournament-starter/blob/main/example_ray_dqn_sp.py) is an example of how you could do it. Also, this linked repo has many algorithms that I used to validate this environment.

Good luck with your experiments!

**Comment by vgainullin** [comment]
Hi @bryanoliveira, 
Thanks for the prompt response. 
Tried changing the variation to EnvType.team_vs_policy and now getting the following error. 
I am running this on my local GPU, so could not try your example via Ray directly, just modified your original example. 
Do you know what the issue might be? 

[INFO] Connected to Unity environment with package version 2.1.0-exp.1 and communication version 1.5.0
INFO:mlagents_envs.environment:Connected to Unity environment with package version 2.1.0-exp.1 and communication version 1.5.0
[INFO] Connected new brain: SoccerTwos?team=1
INFO:mlagents_envs.environment:Connected new brain: SoccerTwos?team=1
[INFO] Connected new brain: SoccerTwos?team=0
INFO:mlagents_envs.environment:Connected new brain: SoccerTwos?team=0
Observation Space:  (672,)
Action Space:  (6,)
Traceback (most recent call last):
  File "/mnt/c/Users/gainu/git/soccer-twos-env/test.py", line 30, in <module>
    3: env.action_space.sample(),
  File "/home/vlad/miniconda3/envs/mlagents/lib/python3.7/site-packages/gym/core.py", line 248, in step
    return self.env.step(action)
  File "/mnt/c/Users/gainu/git/soccer-twos-env/soccer_twos/wrappers.py", line 502, in step
    2: self.opponent_policy(self.last_obs[2]),
TypeError: 'NoneType' object is not subscriptable

**Comment by vgainullin** [comment]
Figured out the previous error. I am able to train using this environment:
env = soccer_twos.make(
    render=False,
    flatten_branched=True,  # converts MultiDiscrete into Discrete action space
    variation=soccer_twos.EnvType.team_vs_policy,
    single_player=False,  # controls a single player while the other stays still
    opponent_policy=lambda *_: 0,  # opponents stay still
)
Is there a way to set up self play without Ray?

Thank you

**Comment by bryanoliveira** [comment]
Hi! Yes, you can use any framework/algorithm to train an agent for this environment. I used Ray in the examples for convenience.
