### ISSUE TITLE
Windows Error: "There should be 'UnityEnvironment_Data'"

### ISSUE THREAD

**Issue by 42jaylonw** [bryanoliveira/soccer-twos-env#6]
OS: windows11 x86_64
I use `pip install soccer-twos` to install this env. 
Got this error when running `env = soccer_twos.make()`:

![image](https://user-images.githubusercontent.com/46954199/218003413-8f43a40f-2957-4423-b9e7-33606a60012e.png)

However, I solved this by manually **renaming the folder 'SoccerTwos_Data' to 'UnityEnvironment_Data' in the site-packages.**
It's nice a RL environment by the way.

**Comment by bryanoliveira** [comment]
Hi @42jaylonw! 

Thank you for pointing that out. I hadn't tested this on Windows recently, so I wasn't aware of this problem. I fixed it for the current release, so it should work for new installs now.

Again, thank you and good luck with your experiments!
